name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: falkordb/falkordb
        ports: ["6379:6379"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Run the default task
      env:
        TEST_REDIS_URL: redis://localhost:6379/0
      run: |
        gem install bundler -v 2.2.15
        bundle install
        bundle exec rake
